export { default as Dashboard } from './Dashboard'
export { default as Patients } from './Patients'
export { default as Appointments } from './Appointments'
export { default as Reports } from './Reports'
export { default as Landing } from './Landing'
